### ISSUE TITLE
Platform node has already been set error

### ISSUE THREAD

**Issue by javimosch** [swimauger/image-classifier#11]
Platform node has already been set. Overwriting the platform with [object Object].
(node:54463) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'whereImpl' of undefined
    at Object.<anonymous> (/home/javi/git/node-image-classification/node_modules/@tensorflow/tfjs-backend-cpu/dist/tf-backend-cpu.node.js:134:39)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/javi/git/node-image-classification/node_modules/tensorset/node_modules/@tensorflow/tfjs/dist/tf.node.js:25:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:54463) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:54463) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
$

**Comment by javimosch** [comment]
Solved by using Node v14.17.1
